name: Deploy after some test
run-name: ${{ github.actor }} for learning step 2 😇
on:
  workflow_dispatch:
#  push:
#    branches:
#      - master

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm start
